name: Docker Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: Build
    steps:
    
    - name: Check out the repo
      run: git clone https://github.com/${{ github.repository }}.git --single-branch repo

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build images
      run: |
        docker build . -t ${{ vars.DOCKERHUB_USERNAME }}/cscods:base
      working-directory: ./repo

    - name: Tag latest images
      run: |
        docker image tag ${{ vars.DOCKERHUB_USERNAME }}/cscods:base ${{ vars.DOCKERHUB_USERNAME }}/cscods:latest

    - name: Push images
      run: |
        docker push -a ${{ vars.DOCKERHUB_USERNAME }}/cscods
